pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3' 
    }
    
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean package'
                  }
                        }
            
    stage ('Deploy') {
      steps {
        script {
          deploy adapters: [tomcat9( path: '', url: 'http://65.1.64.183:8080/')], contextPath: '/pipeline', onFailure: false, war: 'webapp/target/*.war' 
        }
      }
    }
    }
}
