pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3' 
    }
    
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean package'
                  }
                        }
            
    stage('Deploy to Tomcat'){
                    steps{
                        sshagent(['Tomcat']) {
                                         sh 'scp -o StrictHostKeyChecking=no target/*.war ubuntu@65.1.64.183:/opt/apache-tomcat-10.0.16/webapps'
                                             } 
                         }
                       }
            }
}
