pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3' 
    }
    
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean package'
                  }
                        }
            
    stage ('Deploy') {
      steps {
        script {
          scp ubuntu@65.1.114.127:var/lib/jenkins/workspace/demo/target/hello-world.war ubuntu@65.1.64.183:opt/apache-tomcat-10.0.16/webapps
          //deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://65.1.64.183:8080/')], contextPath: '/hello-world.war', onFailure: false, war: 'webapps/*.war' 
        }
      }
    }
    }
}
